apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/${{ parameters.application_source | parseRepoUrl | pick('organization') }}/argocd-example-apps
    path: helm-guestbook
    targetRevision: HEAD
  destination: 
    name: backstack-vault-2
    namespace: default