apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: restrict-node-size-policy
  annotations:
    policies.kyverno.io/title: Restrict Node Size
    policies.kyverno.io/category: Upbound Crossplane
    policies.kyverno.io/minversion: 1.9.0
    kyverno.io/kyverno-version: 1.9.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/subject: Cluster
    policies.kyverno.io/description: >-
      Create clusters with node size large is not permitted
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: restrict-node-size
    match:
      any:
      - resources:
          kinds:
          - aws.platformref.upbound.io/v1alpha1/Cluster
    validate:
      message: >-
        You cannot create a cluster with node size large
        Please change the node size to small or medium
      deny:
        conditions:
          any:
          - key: "{{request.object.spec.parameters.nodes.size}}"
            operator: Equals
            value: "large"
