apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: eks
  title: New Cluster (EKS)
  description: Request an EKS Cluster to host workloads
  tags:
    - caas
    - eks
spec:
  owner: infrastructure
  type: resource
  parameters:
    - title: Cluster Configuration Parameters
      required:
        - cluster_id
        - region
      properties:
        cluster_id:
          title: Cluster ID
          type: string
          description: ID of this Cluster that other objects will use to refer to it.
        region:
          title: Region
          type: string
          description: Region is the region you'd like your resource to be created in.
        iam_role_arn:
          title: IAM Role ARN
          type: string
          description: The IAM Role ARN to connect as ClusterAdmin.
        version:
          title: Version
          type: string
          description: Kubernetes version of the Cluster
          default: "1.28"
          enum:
            - "1.28"
            - "1.27"
            - "1.26"
            - "1.25"
            - "1.24"
        nodes_count:
          title: Node Group Size
          type: integer
          description: Desired node count, from 1 to 100.
          default: 3
        nodes_instance_type:
          title: Node Instance Type
          type: string
          description: Instance type associated with the Node Group.
          default: t3.small
    - title: Destination
      required:
        - repo_url
      properties:
        repo_url:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        pull_request_branch_name:
          title: Branch name for Pull Request
          type: string
          default: new-cluster-request
  steps:
    - id: template
      name: Fetch cluster claim template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: demo/clusters
        values:
          cluster_id: ${{ parameters.cluster_id }}
          region: ${{ parameters.region }}
          version: ${{ parameters.version }}
          iam_role_arn: ${{ parameters.iam_role_arn }}
          nodes_count: ${{ parameters.nodes_count }}
          nodes_instance_type: ${{ parameters.nodes_instance_type }}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        title: Request for new cluster 
        description: |
          Cluster ID: ${{ parameters.cluster_id }}
          Region:     ${{ parameters.region }}
          Version:    ${{ parameters.version }}
          Nodes:      ${{ parameters.nodes_instance_type }} (${{ parameters.nodes_count }})
        repoUrl: ${{ parameters.repo_url }} 
        branchName: ${{ parameters.pull_request_branch_name }}
  output:
    text:
      - title: Accept Pull Request
        content: |
          Your New Cluster Request has been published to GitHub.

          To finish creating the cluster, review and accept the [pull request](${{ steps['publish'].output.remoteUrl }}) 